/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/litmuschaos/chaos-scheduler/api/litmuschaos/v1alpha1"
	scheme "github.com/litmuschaos/chaos-scheduler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ChaosSchedulesGetter has a method to return a ChaosScheduleInterface.
// A group's client should implement this interface.
type ChaosSchedulesGetter interface {
	ChaosSchedules(namespace string) ChaosScheduleInterface
}

// ChaosScheduleInterface has methods to work with ChaosSchedule resources.
type ChaosScheduleInterface interface {
	Create(ctx context.Context, chaosSchedule *v1alpha1.ChaosSchedule, opts v1.CreateOptions) (*v1alpha1.ChaosSchedule, error)
	Update(ctx context.Context, chaosSchedule *v1alpha1.ChaosSchedule, opts v1.UpdateOptions) (*v1alpha1.ChaosSchedule, error)
	UpdateStatus(ctx context.Context, chaosSchedule *v1alpha1.ChaosSchedule, opts v1.UpdateOptions) (*v1alpha1.ChaosSchedule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ChaosSchedule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ChaosScheduleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ChaosSchedule, err error)
	ChaosScheduleExpansion
}

// chaosSchedules implements ChaosScheduleInterface
type chaosSchedules struct {
	client rest.Interface
	ns     string
}

// newChaosSchedules returns a ChaosSchedules
func newChaosSchedules(c *LitmuschaosV1alpha1Client, namespace string) *chaosSchedules {
	return &chaosSchedules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the chaosSchedule, and returns the corresponding chaosSchedule object, and an error if there is any.
func (c *chaosSchedules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ChaosSchedules that match those selectors.
func (c *chaosSchedules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ChaosScheduleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ChaosScheduleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested chaosSchedules.
func (c *chaosSchedules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a chaosSchedule and creates it.  Returns the server's representation of the chaosSchedule, and an error, if there is any.
func (c *chaosSchedules) Create(ctx context.Context, chaosSchedule *v1alpha1.ChaosSchedule, opts v1.CreateOptions) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chaosSchedule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a chaosSchedule and updates it. Returns the server's representation of the chaosSchedule, and an error, if there is any.
func (c *chaosSchedules) Update(ctx context.Context, chaosSchedule *v1alpha1.ChaosSchedule, opts v1.UpdateOptions) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(chaosSchedule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chaosSchedule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *chaosSchedules) UpdateStatus(ctx context.Context, chaosSchedule *v1alpha1.ChaosSchedule, opts v1.UpdateOptions) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(chaosSchedule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chaosSchedule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the chaosSchedule and deletes it. Returns an error if one occurs.
func (c *chaosSchedules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *chaosSchedules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched chaosSchedule.
func (c *chaosSchedules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
