/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1"
	scheme "github.com/litmuschaos/chaos-scheduler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ChaosSchedulesGetter has a method to return a ChaosScheduleInterface.
// A group's client should implement this interface.
type ChaosSchedulesGetter interface {
	ChaosSchedules(namespace string) ChaosScheduleInterface
}

// ChaosScheduleInterface has methods to work with ChaosSchedule resources.
type ChaosScheduleInterface interface {
	Create(*v1alpha1.ChaosSchedule) (*v1alpha1.ChaosSchedule, error)
	Update(*v1alpha1.ChaosSchedule) (*v1alpha1.ChaosSchedule, error)
	UpdateStatus(*v1alpha1.ChaosSchedule) (*v1alpha1.ChaosSchedule, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ChaosSchedule, error)
	List(opts v1.ListOptions) (*v1alpha1.ChaosScheduleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChaosSchedule, err error)
	ChaosScheduleExpansion
}

// chaosSchedules implements ChaosScheduleInterface
type chaosSchedules struct {
	client rest.Interface
	ns     string
}

// newChaosSchedules returns a ChaosSchedules
func newChaosSchedules(c *LitmuschaosV1alpha1Client, namespace string) *chaosSchedules {
	return &chaosSchedules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the chaosSchedule, and returns the corresponding chaosSchedule object, and an error if there is any.
func (c *chaosSchedules) Get(name string, options v1.GetOptions) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ChaosSchedules that match those selectors.
func (c *chaosSchedules) List(opts v1.ListOptions) (result *v1alpha1.ChaosScheduleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ChaosScheduleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested chaosSchedules.
func (c *chaosSchedules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a chaosSchedule and creates it.  Returns the server's representation of the chaosSchedule, and an error, if there is any.
func (c *chaosSchedules) Create(chaosSchedule *v1alpha1.ChaosSchedule) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("chaosschedules").
		Body(chaosSchedule).
		Do().
		Into(result)
	return
}

// Update takes the representation of a chaosSchedule and updates it. Returns the server's representation of the chaosSchedule, and an error, if there is any.
func (c *chaosSchedules) Update(chaosSchedule *v1alpha1.ChaosSchedule) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(chaosSchedule.Name).
		Body(chaosSchedule).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *chaosSchedules) UpdateStatus(chaosSchedule *v1alpha1.ChaosSchedule) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(chaosSchedule.Name).
		SubResource("status").
		Body(chaosSchedule).
		Do().
		Into(result)
	return
}

// Delete takes name of the chaosSchedule and deletes it. Returns an error if one occurs.
func (c *chaosSchedules) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chaosschedules").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *chaosSchedules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chaosschedules").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched chaosSchedule.
func (c *chaosSchedules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChaosSchedule, err error) {
	result = &v1alpha1.ChaosSchedule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("chaosschedules").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
