/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChaosSchedules implements ChaosScheduleInterface
type FakeChaosSchedules struct {
	Fake *FakeLitmuschaosV1alpha1
	ns   string
}

var chaosschedulesResource = schema.GroupVersionResource{Group: "litmuschaos.io", Version: "v1alpha1", Resource: "chaosschedules"}

var chaosschedulesKind = schema.GroupVersionKind{Group: "litmuschaos.io", Version: "v1alpha1", Kind: "ChaosSchedule"}

// Get takes name of the chaosSchedule, and returns the corresponding chaosSchedule object, and an error if there is any.
func (c *FakeChaosSchedules) Get(name string, options v1.GetOptions) (result *v1alpha1.ChaosSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chaosschedulesResource, c.ns, name), &v1alpha1.ChaosSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosSchedule), err
}

// List takes label and field selectors, and returns the list of ChaosSchedules that match those selectors.
func (c *FakeChaosSchedules) List(opts v1.ListOptions) (result *v1alpha1.ChaosScheduleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chaosschedulesResource, chaosschedulesKind, c.ns, opts), &v1alpha1.ChaosScheduleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChaosScheduleList{ListMeta: obj.(*v1alpha1.ChaosScheduleList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChaosScheduleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chaosSchedules.
func (c *FakeChaosSchedules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chaosschedulesResource, c.ns, opts))

}

// Create takes the representation of a chaosSchedule and creates it.  Returns the server's representation of the chaosSchedule, and an error, if there is any.
func (c *FakeChaosSchedules) Create(chaosSchedule *v1alpha1.ChaosSchedule) (result *v1alpha1.ChaosSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chaosschedulesResource, c.ns, chaosSchedule), &v1alpha1.ChaosSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosSchedule), err
}

// Update takes the representation of a chaosSchedule and updates it. Returns the server's representation of the chaosSchedule, and an error, if there is any.
func (c *FakeChaosSchedules) Update(chaosSchedule *v1alpha1.ChaosSchedule) (result *v1alpha1.ChaosSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chaosschedulesResource, c.ns, chaosSchedule), &v1alpha1.ChaosSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosSchedule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeChaosSchedules) UpdateStatus(chaosSchedule *v1alpha1.ChaosSchedule) (*v1alpha1.ChaosSchedule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(chaosschedulesResource, "status", c.ns, chaosSchedule), &v1alpha1.ChaosSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosSchedule), err
}

// Delete takes name of the chaosSchedule and deletes it. Returns an error if one occurs.
func (c *FakeChaosSchedules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chaosschedulesResource, c.ns, name), &v1alpha1.ChaosSchedule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChaosSchedules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chaosschedulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChaosScheduleList{})
	return err
}

// Patch applies the patch and returns the patched chaosSchedule.
func (c *FakeChaosSchedules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChaosSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chaosschedulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChaosSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosSchedule), err
}
