// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosSchedule":       schema_pkg_apis_litmuschaos_v1alpha1_ChaosSchedule(ref),
		"github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosScheduleSpec":   schema_pkg_apis_litmuschaos_v1alpha1_ChaosScheduleSpec(ref),
		"github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosScheduleStatus": schema_pkg_apis_litmuschaos_v1alpha1_ChaosScheduleStatus(ref),
	}
}

func schema_pkg_apis_litmuschaos_v1alpha1_ChaosSchedule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChaosSchedule is the Schema for the chaosschedules API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosScheduleSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosScheduleStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosScheduleSpec", "github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ChaosScheduleStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_litmuschaos_v1alpha1_ChaosScheduleSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChaosScheduleSpec describes a user-facing custom resource which is used by developers to create a chaos profile",
				Properties: map[string]spec.Schema{
					"appinfo": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html Appinfo contains deployment details of AUT",
							Ref:         ref("github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ApplicationParams"),
						},
					},
					"chaosServiceAccount": {
						SchemaProps: spec.SchemaProps{
							Description: "ChaosServiceAccount is the SA specified for chaos runner pods",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"experiments": {
						SchemaProps: spec.SchemaProps{
							Description: "Consists of experiments executed by the engine",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ExperimentList"),
									},
								},
							},
						},
					},
					"schedule": {
						SchemaProps: spec.SchemaProps{
							Description: "Execution schedule of batch of chaos experiments",
							Ref:         ref("github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.Schedule"),
						},
					},
				},
				Required: []string{"appinfo", "chaosServiceAccount", "experiments", "schedule"},
			},
		},
		Dependencies: []string{
			"github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ApplicationParams", "github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ExperimentList", "github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.Schedule"},
	}
}

func schema_pkg_apis_litmuschaos_v1alpha1_ChaosScheduleStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChaosScheduleStatus derives information about status of individual experiments",
				Properties: map[string]spec.Schema{
					"experiments": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html Detailed status of individual experiments",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ExperimentStatuses"),
									},
								},
							},
						},
					},
				},
				Required: []string{"experiments"},
			},
		},
		Dependencies: []string{
			"github.com/litmuschaos/chaos-scheduler/pkg/apis/litmuschaos/v1alpha1.ExperimentStatuses"},
	}
}
